backtest:
  name: "LazySwing PDD Dev"
  version: "v1"
  initial_cash: 100000
  start_date: "2023-04-01"
  end_date: "2024-12-31"

data_source:
  type: "csv_file"
  parser: "binance_kline"
  params:
    file_path: "data/backtests/PDD-5m-2023-2026.csv"
    symbol: "PDD"

strategies:
  - type: "lazy_swing"
    params:
      supertrend_atr_period: 10
      supertrend_multiplier: 2
      cost_per_trade_pct: 0.05
