session_ttl_hours: 24
users:
  - email: yasmas@gmail.com
    password_hash: $2b$10$h3xqfCGEg4DuXrKSjz90o.Jjkf.rajIuflmy34XAILPQMhbFspMvO
    admin: true
  - email: testuser@test.com
    password_hash: $2b$10$dihQkhWU9Hfqd5nFZQ1Pree2BZobQKJr2EaPJ/troZDbp7TLKR9ku
