session_ttl_hours: 24
users:
  - email: yasmas@gmail.com
    password_hash: $2b$10$h3xqfCGEg4DuXrKSjz90o.Jjkf.rajIuflmy34XAILPQMhbFspMvO
  - email: testuser@test.com
    password_hash: $2b$10$mcku6hXNbfFKrYkvGJmna.ifHMl4KP/ufGUxM.cmNzXixfjZJmnY.
